FROM node:16-slim

WORKDIR /usr/app

COPY package.json .

COPY yarn.lock .

RUN yarn install

RUN yarn global add @babel/node

COPY . .

RUN ls -aslh

RUN yarn run build

EXPOSE 4000

CMD ["yarn", "start"]
