version: '2'
services:
  app:
    build: .
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    command: yarn run start:dev
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    command: mongod --smallfiles --quiet
    volumes:
      - /mongo/db
    ports:
      - 27017:27017
