FROM node:14-alpine

WORKDIR /usr/app

COPY package.json .

COPY yarn.lock .

RUN yarn install

RUN yarn global add @babel/node

RUN ls -aslh

COPY . .

RUN yarn run build

EXPOSE 4000

CMD ["yarn", "start"]
