export { default as notifyIfUpdated } from './notifyIfUpdated'
export { getName } from './getName'
export { detectHotword } from './detectHotword'
export { searchManga } from './searchManga'
export { reactionCollector } from './reactionCollector'
export { isHaiku } from './isHaiku'
export { createHaiku } from './createHaiku'
